### ISSUE TITLE
The migrations in Alembic are written incorrectly

### ISSUE THREAD

**Issue by DaniilPK** [MassonNN/masson-aiogram-template#17]
**Describe the bug**
Попытка обратиться к табличке после выполнения всех миграций

**To Reproduce**
1. alembic upgrade head
2. any sql query into table user or chat

**Error logs**
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.user_chat - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

**Comment by MassonNN** [comment]
Дело не в миграциях, а в самих релейшенах. Необходимо дополнительно указать foreign_keys в релейшене.
